--35. Indica cuál es el género favorito de cada uno de los directores cuando dirigen una película

--CONTAR TOTAL DE GENEROS POR PELICULA DE CADA DIRECTOR
--AGRUPAR POR GENEROS
--MOSTRAR EL MAYOR DE CADA DIRECTOR

SELECT D.DIRECTOR_NAME , MAX (G.GENRE_NAME)
FROM PUBLIC.MOVIES M
INNER JOIN PUBLIC.DIRECTORS D ON D.DIRECTOR_ID = M.DIRECTOR_ID
INNER JOIN PUBLIC.GENRES G ON G.GENRE_ID = M.GENRE_ID
GROUP BY D.DIRECTOR_NAME
ORDER BY D.DIRECTOR_NAME;